blank_issues_enabled: true
contact_links:
  - name: "💬 Kodi Forum Thread"
    url: "https://forum.kodi.tv/showthread.php?tid=388459"
    about: "Discuss the addon on the Kodi forum / Обсудить аддон на форуме Kodi"
